const sagaActions = {
  AUTH_LOGIN: "AUTH_LOGIN",
  FETCH_GENRE: "FETCH_GENRE",
  FETCH_BOOK: "FETCH_BOOK",
  EDIT_GENRE: "EDIT_GENRE",
  EDIT_BANNER: "EDIT_BANNER",
  FETCH_BANNER: "FETCH_BANNER",
  FETCH_BANNER_BY_ID: "FETCH_BANNER_BY_ID",
  FETCH_ORDER: "FETCH_ORDER",

  FETCH_CART: "FECTH_CART",

  ADD_TO_CART : "ADD_TO_CART",
  INC_CART_ITEM: "INC_CART_ITEM",
  DEC_CART_ITEM: "DEC_CART_ITEM",
  DELETE_CART_ITEM:"DELETE_CART_ITEM",


  ADMIN_FETCH_ORDER: "ADMIN_FETCH_ORDER",
  ADMIN_FETCH_USER: "ADMIN_FETCH_USER",

  SELLER_FETCH_BOOK: "SELLER_FETCH_BOOK",
  SELLER_FETCH_ORDER: "SELLER_FETCH_ORDER",
};

export default sagaActions;
